### ISSUE TITLE
Add option to specify base class of generated scanner

### ISSUE THREAD

**Issue by jafl** [Genivia/RE-flex#115]
Currently, I'm post-processing the output files with search/replace.  If you agree that this is an option that should be added, I can try to work on a PR.

(Of course, the specified class has to extend `reflex::AbstractLexer<reflex::Matcher>`.)

**Comment by Robert-van-Engelen** [comment]
Perhaps use multiple inheritance? I don't see a compelling reason to add a new feature to specify a user-defined base class for `reflex::AbstractLexer<reflex::Matcher>`.

**Comment by jafl** [comment]
It wouldn't be a base class for `AbstractLexer`.  It would be a base class for the generated scanner:

AbstractLexer → MyBaseClass → MyGeneratedLexer

I considered multiple inheritance.  However, in my case, the base class has to inherit from `AbstractLexer` because it needs access to that functionality.

**Comment by genivia-inc** [comment]
> However, in my case, the base class has to inherit from AbstractLexer because it needs access to that functionality.

Not sure why? This has never been necessary in our lexer projects. The protected members of `AbstractLexer` state are all accessible through methods:
~~~
 protected:
  Input                in_;      ///< the input character sequence to scan
  std::ostream        *os_;      ///< the output stream to echo text matches to
  char                *base_;    ///< the buffer to scan in place, if non-NULL
  size_t               size_;    ///< the size of the buffer to scan in place, if nonzero
  Matcher             *matcher_; ///< the matcher used for scanning
  int                  start_;   ///< the current start condition state
  int                  debug_;   ///< 1 if -d (--debug) 0 otherwise:
  std::stack<Matcher*> stack_;   ///< a stack of pointers to matchers
  std::stack<int>      state_;   ///< a stack of start condition states
~~~
It's safer to not use them directly. See the manual on how to use the lexer methods.

**Comment by jafl** [comment]
Maybe I'm just being dumb, but if I have this structure:

AbstractLexer → MyGeneratedLexer
MyBaseClass ↗

How can MyBaseClass call methods defined by AbstractLexer?

**Comment by genivia-inc** [comment]
The abstract class is just that, abstract. But the derived class (generated) inherits these methods. For example, `in()` returns `in_`. Is that not what you want?

**Comment by jafl** [comment]
How can I call `in()` from `MyBaseClass`?

**Comment by genivia-inc** [comment]
Um, you don't, because it's an abstract class. Use the generated class. We typically derive classes from the generated class.

**Comment by jafl** [comment]
In my case, I want to add the same functionality to many different lexers, and that code needs to be able to call functions defined in AbstractLexer. Without the ability to implement this:

AbstractLexer → MyBaseClass → MyGeneratedLexer

I would have to duplicate the code across each lexer. My current solution works, so if you really don’t think it’s appropriate to implement my request, then I’ll stick with what I have.

**Comment by jafl** [comment]
Sorry, I just realized that I never gave you the full picture in the diagrams.  I'm only creating a base class because I want to do this:
```
                            ↗ Lexer1
AbstractLexer → MyBaseClass → Lexer2
                            ↘ Lexer3
```

**Comment by genivia-inc** [comment]
IMHO multiple inheritance makes sense in this scenario: that base class should not be derived from the lexer abstract class to be placed in the middle BEFORE the generated classes. It is not the proper placement from an organizational and access privilege point of view. Your base class can still be derived from the abstract lexer if you want to access its features. Another simpler (perhaps much better) way is to create a template class instantiated with the generated lexer classes and add your shared methods there.

**Comment by jafl** [comment]
OK, thanks for the advice.
