### ISSUE TITLE
When I build with Microsoft Visual Studio, the generated lex always fails to recognize, works correctly with gcc

### ISSUE THREAD

**Issue by bsrsharma** [Genivia/RE-flex#119]
I did these steps:

1. C:\Reflex>reflex.exe -d --flex --bison -yy test.l
2. Got lex.yy.cpp
3. Built it using Microsoft Visual Studio Community 2019 Version 16.10.0
4. I used "Minimized library and cross compiling" option. i.e. 
5. c++ -I. -Iinclude lex.yy.cpp lib/debug.cpp lib/error.cpp \
    lib/input.cpp lib/matcher.cpp lib/pattern.cpp lib/utf8.cpp
6. The generated EXE file runs but fails to recognize _**any pattern. Including a single word**_ 
7. Repeated line 5 with gcc 11.2.0 on Cygwin64
8. The generated EXE runs and recognizes patterns correctly.

**Comment by bsrsharma** [comment]
Did some more testing. The problem seems to be, if I run this example from Lex and Yacc book, Example 1-1, page 3:
........
go { printf("%s: is a verb\n", yytext); }
[a-zA-Z]+ { printf("%s: is not a verb\n", yytext); }
.......
The second line _**always**_ controls the output. So, the input go seems to be recognized as a generic alphabet pattern and not the word go. This does not happen in Flex.

I also have another issue with words getting matched even if only the prefix matches. i.e. input ONN succeeds in matching  with pattern ON. This does not happen in Flex.

**Comment by genivia-inc** [comment]
> The second line always controls the output. So, the input go seems to be recognized as a generic alphabet pattern and not the word go. This does not happen in Flex.

The behavior of RE/flex is the same as Flex. **There is no difference**: a pattern is matched first before a pattern defined afterwards when both match. This is called the "_[longest leftmost match](https://westes.github.io/flex/manual/Why-doesn_0027t-flex-have-non_002dgreedy-operators-like-perl-does_003f.html)_".

- **go** will match only if **go** is not immediately followed by a letter, that will match the second rule.
- **ON** as a prefix will match instead of **ONN** if you enabled option -P (Perl matching). Just don't use option -P to get the longest leftmost match.
