### ISSUE TITLE
Compatibility issues

### ISSUE THREAD

**Issue by ryjer** [Genivia/RE-flex#125]
re/flex is not compatible with this kind of format but flex accept it
```lex
%{
/* C Declaration */
%}

%%
/*  Lex Definitions */
```

**Comment by genivia-inc** [comment]
Not sure what you mean? This works fine (try it). RE/flex does support `%{` and `%}` code blocks after the `%%` when placed in `%{` and `%}` like Flex, see the manual: https://www.genivia.com/doc/reflex/html/index.html#reflex-code-blocks

**Comment by genivia-inc** [comment]
Instead of `%{` and `%}`, a code block can also be indented:
~~~
%%
    /* code block */
pattern action
~~~
Putting `/*` on the left margin is not something I will ever support in RE/flex, because it is ambiguous. There is no way of knowing if it is code or a pattern. Making an exception for `/*` is problematic, if not dead wrong since patterns may start with `/*`.
