### ISSUE TITLE
Not compatible with flex

### ISSUE THREAD

**Issue by ryjer** [Genivia/RE-flex#127]
This is the version
```bash
$ reflex -V
reflex 3.1.0 x86_64-pc-linux-gnu
License BSD-3-Clause: <https://opensource.org/licenses/BSD-3-Clause>
Written by Robert van Engelen and others: <https://github.com/Genivia/RE-flex>
$ flex -V
flex 2.6.4
```
For this file
```flex
%{
#include <string.h>

int yywrap(void)
{
    return 1;
}

%}

%%
.	{printf("hello world!");}

```
flex works well but reflex echoes an error. (This file has 13 rows in total, there is a blank line at the end but github not show.)
```bash
$ reflex test.l 
test.l:12: error: EOF encountered inside an action
```
It sames need a pair of `%%` for reflex.
```flex
%{
#include <string.h>

int yywrap(void)
{
    return 1;
}

%}

%%
.	{printf("hello world!");}

%%
```

**Comment by ryjer** [comment]
There is a blank line at the end
![image](https://user-images.githubusercontent.com/81322816/155717380-1f5ad160-6b3a-4751-a822-8756d7fb52f6.png)
or the flex echoes the EOF error
```bash
$ flex test.l 
test.l:12: EOF encountered inside an action
```

**Comment by genivia-inc** [comment]
A blank line in the rules is fine, as long as there is an ending `%%`.

**Comment by genivia-inc** [comment]
Also, there are some (not many) not-so-well documented features of Flex that RE/flex replicates faithfully. However, bad undocumented (or under documented) features are not replicated because these often cause confusion or result in compilation errors. There are only one or two such cases that I recall are deemed bad.

A missing ending `%%` is not a good feature of Flex nor a bad feature of Flex, but an ugly feature of Flex. It fits between these criteria for RE/Flex to replicate or not. I may replicate it in a future release perhaps.

**Comment by genivia-inc** [comment]
I should add that all Flex features are replicated, but there is at least one bad situation where the interpretation of the Lex/Flex specification is ambiguous when using empty lines or other forms of spacing/indentation. If it's not clearly documented in Flex and the situation is ambiguous then I left it out of reflex. This is what I mean by a "bad" feature.

**Comment by genivia-inc** [comment]
The second `%%` can be omitted in the latest v3.2.2 update.
