### ISSUE TITLE
exceeds complexity limits:  IMAX value 64KB

### ISSUE THREAD

**Issue by TheEngineGuy** [Genivia/RE-flex#14]
I am trying to use RE-flex to port a tokenizer implemented with JFlex.  https://github.com/apache/lucene-solr/blob/master/lucene/analysis/common/src/java/org/apache/lucene/analysis/standard/UAX29URLEmailTokenizerImpl.jflex

A partial port passed test successfully.  A full port failed with error: "exceeds complexity limits."   The IMAX value is set to 64KB and the Pattern::Index is set to uint16.   Is it possible to increase the IMAX size?  My partial port file is attached.  The pattern size is 17KB.

The generated Java file from JFlex is 1.8MB as a comparison. 

Thanks. 
[url.l.txt](https://github.com/Genivia/RE-flex/files/2326464/url.l.txt)

**Comment by genivia-inc** [comment]
Enlarging the max DFA size will be addressed in the upcoming releases very soon. Right now the max is 64K entries in the DFA code table (which is not 64KB but 256KB max). This may sounds small but the code table is a compacted table and in practice this limit is much larger than you typically need for a lexer to tokenize programming languages. DFAs can blow up in size under certain circumstances. I suspect this is the case in your example since 1.8MB is quite large for a set of patterns in a lexer spec of just 17KB!

**Comment by TheEngineGuy** [comment]
Thanks for the explanation.  Overall I like this library.  Still run into the "exceeds complexity" issue sometimes,  but I could rewrite the match to bypass it.

**Comment by genivia-inc** [comment]
Until the expansion option to generate larger DFAs is available, for which I have a design in place, I recommend to use the Boost matcher option to use an underlying NFA for matching. By contrast, DFAs can grow very large in certain (pathetic) cases, but are very fast. NFAs are small but are generally slow (or much slower in pathetic cases).

**Comment by genivia-inc** [comment]
It has been a while, but the latest version of RE/flex has practically no limits on the pattern length and complexity. I redesigned the VM opcodes to allow long jumps. That was a bit of a challenge because I did not want the performance to suffer. The approach still uses 64K words if that fits, but uses larger opcode tables with LONG instruction jumps to locations outside the 64K range of addresses. Also the DFA generator runs faster, which was necessary to handle large patterns. On the other hand, to get the best performance use option `--fast` to generate C++ code instead of VM opcode tables. That code has not changed, but the regex limits on length and complexity are practically gone.
