### ISSUE TITLE
macOS brew formula does not install header files

### ISSUE THREAD

**Issue by donn** [Genivia/RE-flex#25]
[Formula](https://gist.github.com/steakknife/250e316374a07d52d17071aadcc844ec) is missing the installation of header files entirely... Am I misunderstanding something?

**Comment by genivia-inc** [comment]
After `./configure`, `make install` in the Formula installs the reflex tool, the libreflex library, man page, and header files. Will investigate.

**Comment by genivia-inc** [comment]
Found the cause in `Makefile.am` and will release an update v1.1.1 asap.

**Comment by tegtmeye** [comment]
As an FYI, I am very close to having a fully autotoolized build version available to pull from if you want. I'll post when it's ready.

**Comment by genivia-inc** [comment]
Let me release an updated version 3/6 first, because it includes some other updates. What was missing in `reflex/lib/Makefile.am` was a definition of `_HEADERS`:

~~~
reflexincludedir        = $(includedir)/reflex
reflexinclude_HEADERS   = $(top_srcdir)/include/reflex/abslexer.h $(top_srcdir)/include/reflex/absmatcher.h $(top_srcdir)/include/reflex/bits.h $(top_srcdir)/include/reflex/boostmatcher.h $(top_srcdir)/include/reflex/convert.h $(top_srcdir)/include/reflex/debug.h $(top_srcdir)/include/reflex/error.h $(top_srcdir)/include/reflex/flexlexer.h $(top_srcdir)/include/reflex/input.h $(top_srcdir)/include/reflex/matcher.h $(top_srcdir)/include/reflex/pattern.h $(top_srcdir)/include/reflex/posix.h $(top_srcdir)/include/reflex/ranges.h $(top_srcdir)/include/reflex/setop.h $(top_srcdir)/include/reflex/stdmatcher.h $(top_srcdir)/include/reflex/timer.h $(top_srcdir)/include/reflex/traits.h $(top_srcdir)/include/reflex/unicode.h $(top_srcdir)/include/reflex/utf8.h
~~~
