### ISSUE TITLE
std::isalnum asserts on beginning-of-block 'character' in VC++ 2015/2017

### ISSUE THREAD

**Issue by ryanbinns** [Genivia/RE-flex#3]
The beginning-of-block meta-character has the value 257, but the `std::isalnum` implementation provided by Microsoft asserts that the character passed to it in between 0 and 255 inclusive, so it always asserts at the beginning of a block.

The calling place is line 59 of `absmatcher.h`. The simple fix it to add the range-check into the `isword` function to avoid triggering the assert. I have changed it simply as follows:
```c++
/// Check ASCII word-like character `[A-Za-z0-9_]`.
inline int isword(int c) ///< Character to check
  /// @returns nonzero if argument c is in `[A-Za-z0-9_]`, zero otherwise.
{
  // HACK: VC++ std::isalnum() ASSERT()'s that c is within the range 0..255
  return ((c >= 0) && (c <= 255)) && (std::isalnum(c) || c == '_');
}
```
and it works just fine. This could of course be made conditional upon compiling with a Microsoft compiler.

**Comment by genivia-inc** [comment]
I'd like to keep this test fast. It's only going to test a limited range because of the meta symbols from 0x100 to 0x10C (metas are for boundaries, anchors, and indent). I would consider the following change more efficient. It can still reject the meta chars and reject EOF:

~~~
/// Check ASCII word-like character `[A-Za-z0-9_]`, permitting the character range 0..303 (0x12F) and EOF.
inline int isword(int c) ///< Character to check
  /// @returns nonzero if argument c is in `[A-Za-z0-9_]`, zero otherwise.
{
  return std::isalnum((unsigned char)c) || c == '_';
}
~~~

**Comment by RuudRietvink** [comment]
This also occurs with other std functions like isalpha
