### ISSUE TITLE
Consider changing −s to -s in the user guide

### ISSUE THREAD

**Issue by donn** [Genivia/RE-flex#30]
https://www.genivia.com/doc/reflex/html/

A lot of dashes (-, ascii 45) are replaced with a similar unicode character (−)

```swift
  3> "-".utf8.map { print($0) }
45

  4> "−".utf8.map { print($0) }
226
136
146
```

I spent right about an hour tearing my hair out before I discovered the dashes are different...

**Comment by genivia-inc** [comment]
I worried about this. I made this decision because I did not expect people to copy-paste directly from the documentation page. The command-options are fairly short to type.

The reason I used Unicode minus signs U+2212 has to do with the fact that two regular dashes (aka. hyphens) `--` are easily confused for a single dash in some browsers and platforms when browsing the documentation. This pair typically ends up as one slightly longer dash due to. I really dislike these kind of "readability optimizations" that moderns browsers attempt. Similar renditions occur with `fi` and `fl` [encoded ligatures](https://en.wikipedia.org/wiki/Typographic_ligature#Ligatures_in_Unicode_(Latin_alphabets) ) represented as one character displayed, but fortunately these can still be easily recognized as two letters. But a pair of dashes may not be.

I propose the following small change to `src/reflex.cpp` to support Unicode minus signs for command-line options, which allows copy-pasting from the documentation without getting errors:

~~~
    const char *arg = argv[i];
    if (*arg == '-'
     || (arg[0] == '\xE2' && arg[1] == '\x88' && arg[2] == '\x92') // UTF-8 Unicode minus sign
#ifdef OS_WIN
     || *arg == '/'
#endif
     )
    {
      bool is_grouped = true;
      if (arg[1] == '\x88' && arg[2] == '\x92') // UTF-8 Unicode minus sign
        arg += 2;
      while (is_grouped && *++arg)
      {
        switch (*arg)
        {
          case '\xE2':
             if (arg[1] != '\x88' || arg[2] != '\x92') // UTF-8 Unicode minus sign
               break;
             arg += 2;
             // fall through
          case '-':
~~~

**Comment by donn** [comment]
Oh, I see. That's a good point. Also, `--flex` I can deal with, but I'm a bit too lazy with something like `--bison-cc-namespace=`. 

Though I'm of the opinion that in situations where − is used, it should just give the user a warning and treat it as a file, not as an argument. Just for the sake of consistency, if anything.
