### ISSUE TITLE
Contiguous Unicode Lexing Issue

### ISSUE THREAD

**Issue by suleimanmashini** [Genivia/RE-flex#33]
Hi, When I try to lex using the following rules:

```
٠           {ss << L"0";}
١           {ss << L"1";}
٢           {ss << L"2";}
٣           {ss << L"3";}
٤           {ss << L"4";}
٥           {ss << L"5";}
٦           {ss << L"6";}
٧           {ss << L"7";}
٨           {ss << L"8";}
٩           {ss << L"9";}
؛           {ss << L";";}
،           {ss << L",";}
[\p{IsArabic}_]+     {ss << wstr();}    
.            {ss << wstr();}
 ```
Everything seems fine, so when I lex:
٠  I get 0
and when I lex
٠  ٠  I get 0 0
but when I try
٠٠٠٠٠ I'm given  ٠٠٠٠٠ 
Whats confusing me is the fact that its not matching to the first rule, which has a higher precedence. Thanks for the help!

**Comment by genivia-inc** [comment]
This is expected behavior for a POSIX matcher. Please read about the POSIX versus Perl-like matching differences in the manual https://www.genivia.com/doc/reflex/html/index.html#reflex-posix-perl . In general, a lexer uses POSIX leftmost longest matching policy, which selects the pattern that gobbles up the most input text.

A simple trick is to use a lookahead (aka. trailing context) for each pattern, to make sure the patterns match the same length of input.  Something like this:

~~~
Arabic    [\p{IsArabic}_]+
%%
٠/{Arabic}           {ss << L"0";}
١/{Arabic}           {ss << L"1";}

{Arabic}     {ss << wstr();}
.            {ss << wstr();}
%%
~~~

**Comment by genivia-inc** [comment]
By the way, you could consider using `-m boost-perl` to use the Perl matching mode, which changes the behavior as you may expected, i.e. matching the first rule to the last in that order.
