### ISSUE TITLE
How to add parameters to lexer function?

### ISSUE THREAD

**Issue by LmTinyToon** [Genivia/RE-flex#36]
Is there any way to add parameters to yylex function, which must be compatible with flex/bison? In flex I used redefined YY_DECL macro, but as I understand it does not work in reflex. Generated source code uses such piece of code:

    YY_EXTERN_C int yylex(void)
    {
      int ret = YY_SCANNER.yylex();
      yytext = const_cast<char*>(YY_SCANNER.YYText());
      yyleng = static_cast<yy_size_t>(YY_SCANNER.YYLeng());
      yylineno = static_cast<int>(YY_SCANNER.lineno());
      return ret;
    }

**Comment by genivia-inc** [comment]
The `YY_DECL` macro is extremely ugly, a C hack.

In C++ flex/bison you can extend the `yylex()` parameter list by just defining your own lexer class derived from `yyFlexLexer`, assuming you use `reflex --flex` (or from `Lexer` otherwise), see https://www.genivia.com/doc/reflex/html/index.html#reflex-inherit for explanation.

This allows you to add a new `yylex()` method with the extra parameters you want to handle.

Assuming you're using `reflex --bison` and you're not defining `YY_EXTERN_C` to `"C"` in your code, which you don't need to do, then you can now declare your own new global `yylex(...)` function to override the generated `yylex()` function. Your `yylex(...)` function should call `YY_SCANNER.yylex(...)` similar to the generated code, snf pass the parameters along as you had defined in your `yylex(...)` method of your derived lexer class.

There are other ways that are nicer, e.g. with `--bison-bridge` that passes the lexer object along with its state that you can update anywhere (see `examples/flexexample4.y`), but my suggestion should keep things tidy using just `--flex` and `--bison` if you prefer that.

Note that `--bison-bridge` also allows an extra parameter to be passed using `%extra-type` option as explained in "Advanced Flex and Bison" by John Levine and this works in RE/flex too. However, a more modern approach is to use `--bison-cc` and `--bison-complete`.

**Comment by LmTinyToon** [comment]
@genivia-inc , I am sorry for late. Great thanks for reply. Approach with inheriting works
