### ISSUE TITLE
start states

### ISSUE THREAD

**Issue by RuudRietvink** [Genivia/RE-flex#48]
It would be helpful to have a exclusion of a state:

`
<~SOMESTATE>"if"    return yy::parser::make_IF(location());`

or:
```
<~SOMESTATE>{
// all keywords are no longer recognized as keywords when in state SOMESTATE
}
```

**Comment by genivia-inc** [comment]
That's interesting. It would be a shorthand form for `<S1,S2,Si-1,...,Si+1,Sn>` to exclude state `Si`. And `<~S1,~S2>` could be a shorthand for all states except `S1` and `S2`. However, `<S1,~S2>` for example wouldn't make sense, because `S1` is already included. So perhaps the negation applies to all states in `<~...>`. Food for thought...

**Comment by RuudRietvink** [comment]
Probably <^...> would be more in line with regular expressions,

**Comment by genivia-inc** [comment]
If you want, you could fork the project and modify `src/reflex.cpp`:1014 to check for `^`:

```
/// Get start conditions <start1,start2,...> of a rule
Reflex::Starts Reflex::get_starts(size_t& pos)
```

There are two scenarios to cover:
1. `<^...>` is specified at the top level, if we allow that. In that case we take all of the inclusive start conditions and remove the start conditions specified. This defines the current scope.
2. `<^...>` is specified nested inside another `<...>` scope or scopes. This removes the specified start conditions from the outer scope(s).

The logic at line 1413-1419 increases the scope with the specified start conditions for the case where `<...>{...}` is used. To remove conditions requires a significant change to `get_starts`, for example to take other parameters including the current scope(s) to modify. The logic after this call requires some work too.

**Comment by RuudRietvink** [comment]
Will try.

**Comment by genivia-inc** [comment]
I've changed my mind on specifying all states as negative with `<^...>`, but rather we should allow each state in `<...>` to be specified as positive (added) or negative (subtracted) from the scope.

That is, the following scoping structures should be possible:

    %s A B C

    %%

    <B,C>{
    pattern    action    // rule for states B and C
    <A,^B>{
    pattern    action    // rule for states A and C
    }
    }

    <*,^A,^C>pattern    action    // rule for states INITIAL and B (all states except A and C)

    %%

IMO this structure is more flexible and logical.

I believe we still need to use `^` because the character pair `<^` is an invalid regex pattern (anchor `^` makes no sense after `<`) so it is easy to distinguish it as a scope, which avoids clashing start condition scopes with valid regex patterns. By contrast, `<~`, `<!`, and `<-` can all be a starting valid regex patterns and should be avoided.

**Comment by RuudRietvink** [comment]
<A,^C> is the same as <^C> when A is inclusive
combining them makes no sense.

**Comment by genivia-inc** [comment]
`<A,^C>` at the top level makes no sense, but nested makes sense. At the top level you can do things like `<*,^C>` which makes sense. So we should not assume anything about inclusive/exclusive states when dealing with scopes, because inclusive states only apply to patterns that have no scope. So specifying `<A,^C` or just `<^C>` would make no sense because we use a scope that assumes nothing about the inclusive states versus exclusive states, and does not magically add all inclusive states. That was my original issue with the notation and confusion that can bring with it.

**Comment by genivia-inc** [comment]
I got to this point by writing the documentation of this new feature. Generally speaking, if the documentation of the feature gets complicated there is usually an issue with the feature. Think syntax versus semantics. If the semantics of a syntactic feature are hard to describe (some exceptions etc.) then the feature is doomed.

The documentation is fairly straightforward:

Start condition scopes may be nested.  A nested scope extends the scope of
start conditions that will be associated with the rules in the nested scope.

For example:

    %s A
    %x X

    %%

    pattern    action    // rule for states INITIAL and A

    <A>{
    pattern    action    // rule for state A
    <X>{
    pattern    action    // rule for states A and X
    }
    }

    <X>{
    pattern    action    // rule for state X
    <A>{
    pattern    action    // rule for states A and X
    }
    }

    %%

Designating a start condition as inclusive or exclusive is effective only for
rules that are not associated with a start condition scope, i.e. the difference
between these two types of start conditions only applies to the first rule
given in this example.

Note: Contrary to some Flex manuals, rules cannot be indented in a start
condition scope in Flex and RE/flex.  When a code block is specified indented
at the begin of a start condition scope it is considered an initial code block,
see reflex-code-blocks.

RE/flex extends the syntax of start conditions scopes beyond Flex syntax, to
remove start conditions from the current scope.  A start condition name
prefixed with the `^` operator is removed from the current scope:

    %s A B C

    %%

    <B,C>{
    pattern    action    // rule for states B and C
    <A,^B>{
    pattern    action    // rule for states A and C
    }
    }

    <*,^A,^C>pattern    action    // rule for states INITIAL and B (all states except A and C)

    %%

Note that scopes should be read from outer scope to inner scope, and from left
to right in a `<...>` scope declaration.  This means that `<*,^A,^C>` first
extends the scope to include all start conditions and then removes `A` and `C`.

A start condition cannot be removed when it is not included in the current
scope.  For example, `<*,^A>` is correct but `<^A,*>` is incorrect.

**Comment by genivia-inc** [comment]
I've implemented a version of RE/flex that handles this case and fixes the issue that RE/flex had different nested scope semantics (overriding) than Flex (extending). So a fix with the addition was not too difficult to make while I was working on this fix.
