### ISSUE TITLE
Issues with indentation detection

### ISSUE THREAD

**Issue by RuudRietvink** [Genivia/RE-flex#49]
I have the rule:
`
(?^^\h+/"/*")      // ignore indent changes`

to ignore indentation before comments, but this doesn't work for comments at the start of the line without spaces.
Changing the + into a * doesn't work.

**Comment by genivia-inc** [comment]
Just use `(?^^"/*"|^\h+"\*")`

**Comment by RuudRietvink** [comment]
That removes the /* from the inputstream

**Comment by genivia-inc** [comment]
The problem with that is that empty patterns do not match, and should never do so. So for example `(?^^\h*/"/*")` cannot match empty before a `/*`. It must match something before the tailing context. If that has to be part of your lexical analyzer, you will have to consume `/*` and everything after that till the first `*/`.

**Comment by RuudRietvink** [comment]
So basically the whole indentation mechanism can't be used without hacking.
Also I can't just consume everything until the first */ because I want nested comments.

**Comment by genivia-inc** [comment]
To consume something before the trailing context, it is worth trying `(?^^\n/"/*")`.

**Comment by genivia-inc** [comment]
Perhaps the most elegant approach would be to add a new anchor, say `\k` that kills a dedent/indent when detected there so that dedent/indent stops won't change.

**Comment by RuudRietvink** [comment]
Yes, because I don't want to have any indents/dedents on blank lines too  for instance.
That would be a good thing to control it.

**Comment by genivia-inc** [comment]
I thought about this for a minute. Let me explain what I believe is a simple approach that should logically make sense, meaning that it does not feel like a bad hack. I'm a bit creative here, but I think there is a simple workaround to get around the limitation that `/*`-comments on the first column cannot be matched with `(?^^\h*/"/*")` as trailing context (because the match would be empty).

I'm using the fact that if any `/*` in the first column triggers a dedent, then that dedent should be consumed with `^"/*"\j`. We have no choice but to consume the dedent here, otherwise the dedent will be matched by another rule. We restore the stop positions after scanning the `/*` comment.

The following works, as far as I can tell after some testing. Note that the following lexer spec saves the stop positions in a variable (since push/pop is overkill) and retrieves them later after a `/*`-comment (with possible nested `/*`-comments) is scanned. Let me know what you think:

```
%{
  int level;                 // a variable to track the /*-comment nesting level
  std::vector<size_t> stops; // a variable to save the stop positions after indent
%}
%o main tabs=8
%x COMMENT
%%
^\h+           out() << "| ";               // nodent, text is aligned to current margin column
^\h*\i         out() << "> ";               // indent
               stops = matcher().stops();   // save the stop positions
^"/*"\j        level = 1;                   // do not count dedent(s) to the first line that has a /*-comment
               start(COMMENT);              // skip comment
^\h*\j         out() << "< ";               // dedent
\j             out() << "< ";               // dedent, triggered for each extra level dedented
(?^^\h*\n)     // eat empty lines without affecting indent stops
(?^^\h+/"/*")  // eat white space before /*-comments without affecting indent stops
"/*"           level = 1;
               start(COMMENT);              // continue w/o indent matching
(?^\\\n\h*)    // lines ending in \ continue on the next line
.|\n           echo();                      // ECHO character
<COMMENT>{
"/*"           ++level;                     // allow nesting /*-comments 
"*/"           if (--level == 0)
               {
                 matcher().stops() = stops; // restore the indent margin/tab stops
                 start(INITIAL);            // back to initial state
               }
.|\n           // ignore all content in comments
}
%%
```
We can make this a bit more efficient with `stops.swap(matcher().stops())` to save the stops and `matcher().stops().swap(stops)` to restore the stops.

This is just a viable concept.  If you have trouble with it let me know.

**Comment by genivia-inc** [comment]
Let me add to this that a new anchor, say `\k` would simplify this somewhat as there won't be a need to save and restore the stops. The pattern to match a comment on the first column would be `^"/*"\k` to kill any dedents generated that are caused by its position on the line. Further research is necessary to give a definitive answer whether a new anchor`\k` would be best.

**Comment by genivia-inc** [comment]
A prototype is ready with the new `\k` anchor. With this anchor the following is possible to ignore/kill any indent/dedent changes caused by the placement of a `/*` anywhere from the left margin. The `\k` has simply no effect if a `/*` is placed anywhere else, e.g. after a statement:

```
%x COMMENT
%%
^\h+           out() << "| ";    // nodent, text is aligned to current margin column
^\h*\i         out() << "> ";    // indent
^\h*\j         out() << "< ";    // dedent
\j             out() << "< ";    // dedent, triggered for each extra level dedented
(?^^\h*\n)     // eat empty lines without affecting indent stops
(?^^\h+/"/*")  // eat white space before /*-comments without affecting indent stops
"/*"\k         level = 1;        // /*-comment, kill any dedent/indent changes that may be caused by the placement of /*
               start(COMMENT);   // continue w/o indent matching
(?^\\\n\h*)    // lines ending in \ continue on the next line
.|\n           echo();           // ECHO character
<COMMENT>{
"/*"           ++level;          // allow nested /*-comments 
"*/"           if (--level == 0)
                 start(INITIAL); // back to initial state
.|\n           // ignore all content in comments
}
%%
```

Like the other anchors `\i` and `\j`, `\k` should be placed at the end of a regex pattern, otherwise it is not effective (and perhaps should be flagged as an error).

I need more testing to verify the behavior before releasing an update.
