### ISSUE TITLE
Question: about {token}

### ISSUE THREAD

**Issue by RuudRietvink** [Genivia/RE-flex#55]
Is there a way to nest {token}s in a [ ] regex?
Like:
```

num   [0-9]
letter [a-z]
all   [{letter}||{num}]
```

**Comment by genivia-inc** [comment]
No, this is not possible. The syntax of character classes is restricted with a good reason: to avoid normal use of characters in classes from being interpreted as special. Otherwise ambiguities arise, e.g. `[{a}]` can be a class with characters `{`, `a`, `}` or a class with substituted `{a}`. The reason `||[...]`, `--[...]` and `&&[...]` are non-ambiguous is clear from the double use of characters as markers (`||` and `&&`) that you don't expect in a class, e.g. `[\w--[0-9]]`.

Also `{num}{+}{letter}` cannot be used, because the operands to `{+}` must be literal classes. I had considered this as a feature in the past (to expand the definitions), but ran into issues in the regex parser implementation. It would be more complex to implement than would initially appear for this mundane syntax.

Flex does not handle these forms either with `{name}` definitions. It accepts `[0-9]{+}[a-z]`. Actually, that feature is not well documented in Flex and I kind of stumbled upon it by accident if my memory serves me well.

**Comment by RuudRietvink** [comment]
I propose a thing like:

num   0-9
letter a-z
all   [\d{letter}\d{num}]
```
Or another \x letter that has no meaning yet.

**Comment by genivia-inc** [comment]
Most escapes such as `\d` already have a meaning and may have to be avoided for reasons of backward compatibility (`[\d{name}]` is a valid character class with `[0-9aemn{}]`).

Also, `num` and `letter` are not character classes, which they should be to stay within the intended semantics of character class operations (union, intersection, and subtraction). Operations on character classes should expect character classes as operands. 

I figured I could implement the following without breaking existing conventions regarding regex syntax and semantics.

1. This is already possible fortunately: the character class union, intersection, and subtraction operations are left associative and have the same operator precedence.  Operations can be chained together, for example `[a-z||[A-Z]--[aeiou]--[AEIOU]]`, `[a-z--[aeiou]||[A-Z]--[AEIUO]]`, `[a-z&&[^aeiou]||[A-Z]&&[^AEIOU]]`, and `[B-DF-HJ-NP-TV-Zb-df-hj-np-tv-z]` are the same character classes.

2. Using an escape such as `\d{name}` could work, but why bother?  A lexer specification may use a defined name in place of the second operand of an union, intersection, and subtraction operation, if the defined name expands into a character class.  For example:

    lower     [a-z]
    upper     [A-Z]
    letter    [_||{lower}||{upper}]
    alnum     [0-9||{letter}]
    name      {letter}{alnum}*
    %%
    {name}    std::cout << "name: " << text() << std::endl;
    .|\n      // skip everything else
    %%

3. Perhaps unfortunately, we may never allow the placement of a defined name as the first operand to a union, intersection, and subtraction operation, because the definition is not expanded as the first `{` is not reserved in any way. The name and the `{`, `}` characters are literally included in the resulting character class.  For example, `[{lower}||{upper}]` contains
`[A-Zelorw{}]`.

The `reflex::convert` algorithm constructs a regex from a lex-like pattern that any regex engine understands. This algorithm is not a full parser, but scans and converts the pattern from left to right while expanding defined names. There are some reasonable limitations what should be done.

**Comment by genivia-inc** [comment]
This approach works as tested and implemented right now. I'll release an update unless there is a breaking issue in further testing, which I doubt because the current regex syntax for bracket lists is not affected with this addition.

**Comment by RuudRietvink** [comment]
I propose a thing like:

num   0-9
letter a-z
all   [\d{letter}\d{num}]
```
Or another \x letter that has no meaning yet.

**Comment by RuudRietvink** [comment]
This gives an error on reflex 1.3.2 WIN:

```
superscriptNrs  [⁰¹²³⁴⁵⁶⁷⁸⁹]
superscript     [||{superscriptNrs}]
``````

error: malformed regular expression or unsupported syntax
error in regex at position 18
[||{superscriptNrs}]
                  \___invalid character class range

**Comment by genivia-inc** [comment]
Weird. I think a logic check is broken somewhere after building, since the implementation and tests worked.

**Comment by genivia-inc** [comment]
I figured you're using `%option unicode`. You can't use this construct with Unicode.

**Comment by RuudRietvink** [comment]
The documentation is a bit confusing regarding unicode or non-unicode. What is allowed when and when not.
