### ISSUE TITLE
Benchmarks for re2c

### ISSUE THREAD

**Issue by certik** [Genivia/RE-flex#56]
According to my benchmarks, [re2c](http://re2c.org/) also seems to be faster than flex. So it would be interesting to compare it against RE-flex in the table in README.

**Comment by genivia-inc** [comment]
Thanks for sharing your suggestion.

When lexical analyzer generators claim to be faster than Flex, it is often not clear what version of Flex is used and which options were enabled. I have a problem with that and therefore I think it is important to show the actual improvement over the **fastest** Flex options. There are major differences in the performance of Flex options, with `flex --full` the fastest, see also e.g. http://nothings.org/computer/lexing.html.

Both RE/flex and re2c are high performance and competitive, and one versus the other may win on (minor) performance differences depending on features enabled or disabled, the structure of the lexer specifications, and the type of input scanned.

I have four reasons why I personally think its not a good idea to compare the performance of RE/flex competitors (other than Flex):

1. Decisions to use a analyzer generator should not just be taken on performance considerations alone, because features affect performance. For example, RE/flex has all features enabled by default (line and column counting, indent tracking and matching, support for special anchors, etc.), which all do incur some overhead. Turning these off makes RE/flex even faster, but less usable. So what features should be enabled when comparing performance?

2. Performance depends on several factors: the input source (memory is fastest), structure of the lexer specification and choice of regular expressions to avoid common performance bottlenecks with them (avoid lengthy backtracking, e.g. the Lex/Flex manuals point to important performance considerations).

3. RE/flex and other lexical analyzer generators are still evolving. They're only getting faster in the future, making contemporary performance comparisons useless and soon obsolete.

4. Finally, there is also the matter of respect for each others work. We're all putting efforts into improving the software. It's not a matter of one winner takes all, but rather what do we think differently that is important and what do our users think that is important to them to choose one over the other?

This does not mean that I, or someone else, will never compare the performance of re2c, but it is not right or even informative to just add one row with a number in this table that is roughly comparable but without context.

**Comment by certik** [comment]
@genivia-inc thanks for the feedback. I definitely respect everybody's work here. The `flex` code is also evolving, and so using the same argument, one should perhaps not even benchmark against `flex` either. So perhaps the table should be removed completely, and if benchmarking were done, it must be done with all the considerations that you mentioned.

Thanks your feedback!

**Comment by genivia-inc** [comment]
PS: reflex v1.3.5 is now 15% to %30 faster than its previous versions. Running time of the performance test is reduced to just 11ms compared to Flex with fastest option (full) 17ms. In other words, reflex is 50% faster than Flex for this typical usage scenario to scan a C program.
