### ISSUE TITLE
Matches at beginning of line with equal length

### ISSUE THREAD

**Issue by Prototype0** [Genivia/RE-flex#59]
Hi, I'd like to thank you for this useful tool.

With the specifications below and the input "aab" I expected both rules to match the full input and MIXED to be returned because it's first, however it appears to return START_OF_LINE instead. This is also the case with longer inputs containing mixed 'a' and 'b', for example "aabaabbaba".

```
%option fast
%option header-file
%option noline

%top{
	enum token {
		MIXED = 1,
		START_OF_LINE
	};
%}

%%
[ab]*(ab|ba)[ab]* 	return MIXED;
^[ab]+ 			return START_OF_LINE;
%%
```

I was able to get the behavior I was expecting by splitting the second rule as below:
```
[ab]*(ab|ba)[ab]* 	return MIXED;
^a+ 			return START_OF_LINE;
^b+ 			return START_OF_LINE;
```

I also noticed that using the first rule without the anchor `[ab]+` behaves as I would expect (doesn't override MIXED) with the obvious disadvantage of not being anchored to the start of the line.

I didn't see a mention of this in the user guide, is the first set of rules not supported?
I was originally trying to match whitespace at the start of lines with `^\h+` when I encountered this issue.

**Comment by genivia-inc** [comment]
The pattern `^[ab]+` is considered longer than say `[ab]+` when a start of line is matched, because anchors have non-zero weight. This is different with Perl matching, where the ordering of the rules take higher precedence than their length.

When you use option `graphs-file` you will see why this is the case:

<img width="679" alt="dump" src="https://user-images.githubusercontent.com/13117347/67638475-fc2e2980-f8ba-11e9-8b8b-748959d1cd96.png">

Arrows labelled `BOL` match a begin of line, if the pattern was matched at the start of a line. Pattern `[2]` is matched with a higher preference when a `BOL` is detected. We eventually transition to the final state with `[2]` instead of staying in a final state corresponding to pattern `[1]`.

Your second example works sometimes because only matches a non-empty sequence of `a` or `b`, but not a mix:

<img width="555" alt="dump2" src="https://user-images.githubusercontent.com/13117347/67638514-7199fa00-f8bb-11e9-9280-04089509d5cf.png">

**Comment by Prototype0** [comment]
That makes sense, thanks. I didn't realize `BOL` was counted as part of the length, I expected the length would only include the literal characters. In that case it is working as intended.
