### ISSUE TITLE
bison-complete mode handles EOF incorrectly

### ISSUE THREAD

**Issue by Stevie-O** [Genivia/RE-flex#64]
(with Bison v3.4.1, at least)

The default `<<EOF>>` implementation in bison-complete mode looks like this:

```
            if (matcher().at_end())
            {
              return yy::parser::symbol_type();
            }
```

This doesn't actually return an end-of-file indicator (symbol 0), however; instead, it returns an "empty symbol" (symbol -2).  Since that symbol isn't actually in the final grammar that Bison constructs, it causes a parse error at EOF.

The correct expression is `yy::parser::symbol_type(0, location())`.

(As an added bonus, when YYDEBUG is enabled and the tracing code tries to display that symbol, it indexes an array with -2 and segfaults.)

**Comment by genivia-inc** [comment]
The most flexible way to address this is by adding a new option `--token-eof=VALUE` to define the return value when the end of input is reached (or when an error occurred). This value can be specified explicitly by the user to override the default. The default is an empty value, since we invoke the token type default constructor by default. For example, `return int()`.

So for option `--bison-complete` we will implicitly set `--token-eof=0` to `return yy::parser::symbol_type(0)`. If the user wants the location value too, then they need to explicitly specify `--token-eof="0, location()"` to do so. The `location()` is auto-generated, but the user may want to use something else.

The `flexlexer.h` definition of `YY_NULL` will need to be updated too, to make sure that `yyterminate()` returns the proper value, i.e. when option `--flex` is used.

I made the necessary changes to do so.

If you believe that this approach works, then we can release a new version with these updates.

**Comment by genivia-inc** [comment]
Or, alternatively, `--token-eof` could be the default lexer return value at EOF, not the `--token-type` constructor parameter. Perhaps that is more logical?

**Comment by genivia-inc** [comment]
I got it wrong about not passing `location()` too if Bison locations is enabled when Bison complete is used. This parameter is required in that case. To handle all this properly, the `--token-eof` is set to `yy::parser::symbol_type(0)` if Bison locations is disabled and set to `yy::parser::symbol_type(0, location())` if Bison locations is enabled.

The new option `--token-eof=VALUE` (or `%o token-eof=VALUE`) can be used to override the the value returned by the lexer when EOF is reached. This is set automatically with Bison complete, if not set by the user. In other scenarios this option can also be used to override the default return value `token_type()` i.e. the default-constructed token type value.

I think we can wrap this up and release an update soon.

**Comment by genivia-inc** [comment]
Version 1.5.5 adds option `--token-eof` and fixes the Bison complete EOF default case.

**Comment by genivia-inc** [comment]
The default `<<EOF>>` rule was tested with two reflex 1.5.5 lexers: `examples/flexexample11.lxx` and `examples/reflexexample11.lxx`, showing no issues. We also had other projects check on this. All should be good now.

Thanks for reporting this. If there is anything else you run into, let us know!
