### ISSUE TITLE
Support for the %param Bison directive

### ISSUE THREAD

**Issue by dnicolodi** [Genivia/RE-flex#75]
I haven't found an users' mailing list or something similar, thus asking here. Please direct me to a more appropriate venue if it is not appropriate. I just started looking into RE/flex and it looks very interesting!

I am working on a [parser](https://github.com/beancount/beancount/tree/master/beancount/parser) that uses multiple `%param` Bison directives [here](https://github.com/beancount/beancount/blob/master/beancount/parser/grammar.y#L153) to have multiple parameters passed to reentrant scanner (now implemented with Flex) and to the Bison parsers. I would like It seems that RE/flex does not support this. Is it so or am I missing something? Is there interested in supporting this?

**Comment by genivia-inc** [comment]
Thanks for the feedback. That might be a useful feature to add to reflex.

Several of the Bison `.y` file examples included with reflex in the `examples` directory use `%param` to pass extra arguments to the parser (e.g. `yyparse`).

This could be implemented in reflex too, i.e. by introducing a new `%option param="extra params"` option (and its shorthand `%param "extra params"`). These parameters will be added after any parameters that are already passed to `yylex` depending on the `%option bison-xyz` options, such as `%option bison-locations` that passes a `yylloc` object to `yylex`.

If there is some interest in this, then we can add it.

**Comment by genivia-inc** [comment]
[Beancount](https://github.com/beancount/beancount) is a nice project!

I see that `beancount/parser/lexer.l` uses `%option extra-type="yyextra_t*"`, so it looks like old school Flex. Instead, if you are considering RE/flex, you might want to populate the lexer class with `%class` and `%init`. And wow, there are a lot if UTF-8 patterns in `beancount/parser/lexer/*.l` files that appear to be coded by hand. RE/flex auto-generates these for you with patterns like `\p{Li}`, `\p{Lo}`, `\p{Lt}` etc. We also keep our Unicode support up-to-date to the latest standard, currently Unicode 13.

**Comment by dnicolodi** [comment]
> Several of the Bison `.y` file examples included with reflex in the `examples` directory use `%param` to pass extra arguments to the parser (e.g. `yyparse`).

I may be missing something, but a quick `grep` through the examples reveal usage of `%lex-param` and `%parse-param` but none of `%param`. `%param` combines both in a single directive. It seems that reflex only support one of such directives and not multiples ones to pass multiple arguments.

> This could be implemented in reflex too, i.e. by introducing a new `%option param="extra params"` option (and its shorthand `%param "extra params"`). These parameters will be added after any parameters that are already passed to `yylex` depending on the `%option bison-xyz` options, such as `%option bison-locations` that passes a `yylloc` object to `yylex`.

I think the semantic should be defined by what Bison expects to happen when the `%param` directive is used: https://www.gnu.org/software/bison/manual/html_node/Pure-Calling.html

> If there is some interest in this, then we can add it.

One of the attractive things of RE/flex is that it has compatibility with Flex. For example, I was very pleasantly surprised when I found that, despite it targeting C++, RE/flex can also emit code compatible with C Bison projects. It would be great if compatibility could be extended to support this use case.

**Comment by dnicolodi** [comment]
> I see that `beancount/parser/lexer.l` uses `%option extra-type="yyextra_t*"`, so it looks like old school Flex.

Indeed, the scanner definition targets Flex right now.

> And wow, there are a lot if UTF-8 patterns in `beancount/parser/lexer/*.l` files that appear to be coded by hand. RE/flex auto-generates these for you with patterns like `\p{Li}`, `\p{Lo}`, `\p{Lt}` etc. We also keep our Unicode support up-to-date to the latest standard, currently Unicode 13.

This is the main reason why I am exploring substituting RE/flex for Flex. The scanner definition will need to be modified, but I would like to keep the changes contained.

**Comment by genivia-inc** [comment]
Taking a closer look into this for an update.

**Comment by genivia-inc** [comment]
The [Bison documentation](https://www.gnu.org/software/bison/manual/bison.pdf) 4.3.6 states:

`%param {argument-declaration}` . . . [Directive]
Specify that argument-declaration are additional yylex/yyparse argument declaration. This is equivalent to `‘%lex-param {argument-declaration} ... %parse-param {argument-declaration} ...’`. You may pass declarations, which is equivalent to repeating `%param`.

There is no problem using `%param` in Bison files and RE/flex scanners. However, the `yylex` global function (used by bison-bridge Bison pure parsers that are reentrant) does not accept additional arguments when RE/flex is not made aware of these extra arguments, e.g. via a new `%option`. Without this crucial information the global `yylex` function is simply not extended with the extra parameters. This means that we need to update RE/flex to accept one or more `%option param="extra params"` declarations (or its shorthand `%param "extra params")` should resolve this. That is preferable compared to the old-school Flex `YY_DECL` macro mess (`YY_` macros are supposed to be used internally only, so that is an ugly hack).

Another approach is possible, one that requires bison-complete parsers instead of pure parsers. Declare a C++ lexer class with an additional `yylex()` method with the extra parameters. This method should set the lexer class members to the value(s) passed  and call `yylex()` without the extra parameters. The lexer rules use the lexer members:
~~~
%class{
  public:
    int yylex(..., extra *stuff)
    {
       this->stuff = stuff;
       return yylex(...);
    }
  private:
    extra *stuff;
}
~~~
However, this is not perfect either. There is some overhead to set the member(s) of the class. This can be avoided when the extra parameters are simply passed to the `yylex` function, which then executes the lexer rules that access the(se) parameter values directly.

We need to analyze this further and present a solution.

**Comment by genivia-inc** [comment]
Let me add that if you want to pass extra state information to the lexer and parser then it is much cleaner to associate the state information with the lexer class, which is passed to the parser anyway with Bison `%parse-param { Lexer *lexer }`. You don't need all the `extra-type` stuff. Just put that in the `%class{ }` and initialize with `%init{ }`. The parser can use this extra state data via member access, i.e. `lexer->data`.

Anyway, I will add the following new option to RE/flex for an update: `%option lex-params="extra parameters"` which adds the specified parameters to the `yylex` function/method.

**Comment by genivia-inc** [comment]
The v2.1.1 release has a new `%option params="extra parameters"` option to extend the `lex()`/`yylex()` parameters. Note that I choose `%params` instead of `%lex-params`, since that is simpler and there can't be confusion what is extended. See also the updated docs.
