### ISSUE TITLE
Cannot get a pattern to work

### ISSUE THREAD

**Issue by Atmaks** [Genivia/RE-flex#78]
First, I would like to thank you for making this awesome library freely available! Wouldn't know what to do without it. Please tell me if this is not an appropriate place to ask for help with library usage and if you have some kind of discussion board for things like that.

I don't think my issue lies with the library, rather, I cannot figure out the proper regex for my purpose. I'm trying to lex/parse Lua source files for a specific purpose, where lexing is done with the help of RE/flex.
Lua has the concept of "long literal strings" which look like the following: `[==[i'm a string!]==]`, where the amount of `=`s has to match for opening and closing sequences. Here's the pattern I came up with:
````
long_string_start		\[=*\[
long_string_end			\]=*\]
long_string_content		(?s:.*?)/{long_string_end}

%%

{long_string_start}	{
				long_string_equals_count = count_characters(text(),'=');
				current_long_string.clear();
				start(LONG_STRING_LITERAL);
			}

<LONG_STRING_LITERAL>{

{long_string_end}	{
				if (count_characters(text(), '=') != long_string_equals_count)
					current_long_string.append(text());
				else {
					current_token_ = Token{ Literal::STRING, std::move(current_long_string) };
					start(INITIAL);
				}
			}
{long_string_content}	current_long_string.append(text());

}
````
And here's debug output for string `R"([====[a]==]bc]====])"`:
````
--EOF (start condition 0)
--accepting rule at line 96 ("[====[")
--accepting rule at line 112 ("a]==]bc]====")
--accepting default rule
]--EOF (start condition 1)
..\..\..\test_main.cpp(117): error: Expected equality of these values:
  lexer.get_current_token()
    Which is: Token of type Keyword::AND with value
  expected_token
    Which is: Token of type Literal::STRING with value a]==]bc
````
As can be seen in the listing above, the `long_string_content` pattern gobbles up everything up until the last closing bracket, despite lazy quantifier and positive lookahead being used, For the life of me, I cannot figure out why and would appreciate anyone pointing me in the right direction.

**Comment by genivia-inc** [comment]
I really like the way you approached this, with the pattern `(?s:.*?)/{long_string_end}` to match anything up to the ending long string marker. However, just like Lex and Flex, a trailing context is not reliable when it overlaps with the pattern preceding it.

The theoretical explanation is a bit long, bit it boils down to the limitation of the DFA that is constructed. The problem arises when the trailing context (lookahead) pattern overlaps with the pattern preceding it. In that case the DFA states cannot unambiguously identify the start of the trailing context, whether it is part of the first pattern or the lookahead pattern. The RE/flex documentation states this limitation.

A future update of RE/flex might remove this limitation entirely, using [Laurikari submatch addressing](https://laurikari.net/ville/regex-submatch.pdf) or using our [staDFA method](https://www.researchgate.net/publication/333386342_staDFA_An_Efficient_Subexpression_Matching_Method) that we developed. We don't want a quick hack such as Flex that in a few cases allows overlap using a quick check on the length of the trailing context to make a correction. But this check is not consistent and may fail. It also won't work for your cases because the trailing context has a variable length.

I suggest the following:

1. to rewrite the `<LONG_STRING_LITERAL>` block to scan one (wide) character at a time until you get to the end marker. Then check if the end marker's length matches the length of the start marker. If not, you will need to add the text to the string accumulated so far. Otherwise you're done. To accumulate the string you have two options: push the characters onto a (wide) string buffer as you are doing right now or you could use `more()` (or `yymore` with `--flex`) append the next match to the matched text but that also adds the end marker, which has to be stripped off). Note that pushing the characters onto a `std::wstring` wide string has the advantage that the literal string is converted from UTF-8 (or whatever format the input has) on the fly to a wide string.

2. Another approach is to define
~~~
long_string_content		(?s:.*?){long_string_end}
~~~
which includes the possible end marker in the pattern. Then you will have to strip the end marker off or if it does not match the start marker then continue scanning the string e.g. using `more()` (or `yymore`) to accumulate the parts, including the last part with the end marker.

**Comment by Atmaks** [comment]
Thank you for such a detailed response! It seems I wasn't paying enough attention when reading the docs, because now I immediately found the limitation you mentioned.

The approaches you describe seem obvious in hindsight. Actually, I've seen something like the first approach somewhere in the examples, but was worried the performance would noticeably degrade since input would be processed one character at a time. Well, doesn't really matter for source files since those won't be that long.

I believe the issue can be safely closed now.

**Comment by genivia-inc** [comment]
One small suggestion. Watch out for cases where an end marker was found but did not match, when the ending `]` character is the start of the actual end marker. For example, [==[blabla]=]==]`, where `blabla]=` is the long string. This `]` character should be put back on the input and not be part of the match, e.g. with `less(size() - 1)`.
