### ISSUE TITLE
How to get the currently scanned line as a string?

### ISSUE THREAD

**Issue by DaOnlyOwner** [Genivia/RE-flex#8]
Hey, this project is awesome!
Since I don't find any mailinglists I just opened a new issue.
I am trying to get the line that is currently analyzed as a string. Is there a 'native' way or do I have to do it myself?
Cheers

**Comment by genivia-inc** [comment]
Sure, this is certainly possible with a little bit of work as the following example shows.

```
// showlines.l to show lines on which a match was found
%{
std::string line; // the line that holds the line on which a match was found
%}

%%

\n.*    line = text(); matcher().less(1); // keep only \n in the match, so we can advance over the line with other patterns

\d+     |
\w+     std::cout << text() << " found on: " << line << std::endl; // digits and words are printed with the line found (note that a line starts with \n)

.       // ignore everything else in this demo

%%
```

Compile with:
`reflex --main showlines.l`
`c++ -o showlines lex.yy.cpp -lreflex`

Example:
`./showlines < showlinesl`

There is only one caveat: this will not work for the first line in a file scanned, since `line` is not populated until the second line on the input. Perhaps adding `\A.*` as a pattern works to fix this, by matching the start of input with `\A`, but the problem could be that `less(1)` removes its first character and `less(0)` is dangerous as it could lead to infinite matching attempts.

**Comment by DaOnlyOwner** [comment]
Thanks mate ;)

**Comment by genivia-inc** [comment]
A bit late perhaps, but I should add that the RE/flex 1.5.0 has new methods to get the line where the match occurs using two new methods `matcher().line()` and `matcher().wline()` (wide string). A third method, `matcher().span()` extends the match to the entire line.

**Comment by DaOnlyOwner** [comment]
Hello,
that's certainly useful, I will check it out. Thanks for the improvement.
