### ISSUE TITLE
Flex compatible lexer with LexerInput still reads one character from stdin

### ISSUE THREAD

**Issue by dnicolodi** [Genivia/RE-flex#80]
I have a lexer that should be consuming data from a source that is not a file. To implement this I use this code:
```
%class{
    virtual size_t LexerInput(char *s, size_t n)
    {
	return pyfile_read_into(yyget_extra(this)->in, s, n);
    }
}
```
I know that storing the input object is stored in the extra struct is not good form, but I am adapting a Flex lexer specification that uses this way of doing things. I want to get the lexer working before cleaning it up.

When I run the lexer, however, it reads a first character from stdin before switching to read input data via the LexerInput method above (I need to press return in the console to have it continue).  In my application, I do not set the input stream, thus I think it default to stdin, so it is somehow expected that the lexer tries to read from there, however I would have thought that specifying the method above would override this completely. What am I doing wrong?

**Comment by genivia-inc** [comment]
The easiest way to disable stdin initialization is:

    %option nostdinit

Alternatively, just initialize your lexer object with an empty string as input, to force `AbstractLexer::stdinit()` to not return stdin, like so:

    yyFlexLexer lexer("");

Now, because you defined your own `LexerInput()` input stream, that stream will be read instead of an empty string.

Otherwise, in your current scenario, the parser calls `yylex()` without arguments to indicate what to read (which to be expected). This instantiates a matcher object with input from `AbstractLexer::stdinit()`, which returns stdin by default if no input was assigned already before the lexer starts with `yylex()`. This in turn reads the first byte to determine if the input has a UTF BOM. If so, it switches to the UTF mode to decode. So the problem is that no input was specified anywhere until this point.

I agree that this is perhaps not ideal, but a consequence of supporting all the possible UTF input formats automatically, even for stdin.

We cannot make `nostdinit` a default option, because there are use cases when stdin should be read when no input is specified whatsoever.

I think that somewhere in the documentation this should be made more clear, perhaps?

**Comment by dnicolodi** [comment]
Thanks for the explanation. This makes sense and indeed maybe should be documented where `LexerInput()` is introduced.

I added the `nostdinit` and now the lexer does not attempt to read from stdin anymore. However, the first time I run the lexer in my program the first call to `yylex()` takes a very long time, of the order of 1.5 seconds. Subsequent calls to `yylex()` are fast as expected. Destroying and creating another lexer and invoking `yylex()` does not incur in the delay either. It seems that something is initialized when `yylex()` is called the first time.

One more thing: is there a way to reuse the encoding conversion mechanism used to read from files? I would like to provide data not from a file but still be able to support other encodings than utf8.

**Comment by genivia-inc** [comment]
> It seems that something is initialized when yylex() is called the first time.

That is the overhead of pattern conversion to virtual machine code. Use option `--full` to statically produce the machine in tables or `--fast` to produce the machine in direct C++ code.

**Comment by dnicolodi** [comment]
That was it. Thank you!

**Comment by genivia-inc** [comment]
`LexerInput` bypasses `reflex::Input` altogether. The `reflex::Input` decoders are applied to `FILE*` input. Borrowing code from `reflex::Input` would be my best guess to convert input of code pages to UTF-16 like `reflex::Input` does. Then for UTF-16/32 decoding some trickery is needed that requires keeping the decoding state to normalize UTF-16/32 finally down to UTF-8. C++11 has some nice additions that can help you out with [codecvt](https://en.cppreference.com/w/cpp/locale/codecvt).

**Comment by genivia-inc** [comment]
A quick clarification: as long as `LexerInput` produces UTF-8, then you're good without making any changes. The lexer specification can use unicode patterns.

**Comment by genivia-inc** [comment]
Another approach that is simpler is to populate a (wide) string first, then assign that as input to the scanner. This can be a wide string with Unicode code points or a regular 8-bit string with UTF-8. These string can be converted first, before passing them to the scanner, if you want to support non-Unicode code pages. Strings can be `char*`, `wchar_t*`, `std::string`, and `std::wstring`.

**Comment by dnicolodi** [comment]
I am somehow out of my comfort zone here and I am not sure what you mean with "wide string with Unicode code points". I thought that Unicode needs to be always encoded somehow and that `wchar_t` does not define how this should be done (what a `wchar_t` is is not really defined either, ie 2 bytes vc 4 bytes). How does RE/flex know what encoding is used in a wide string?

**Comment by genivia-inc** [comment]
Wide strings really just contain UCS4 or UTF-16 with surrogate pairs for larger code points. The `reflex::Input` wide string input converts this to UTF-8 for matching by checking for UTF-16 with surrogate pairs. An error character `REFLEX_NONCHAR` (U+FFFD) is produced for non-compliance. UTF-8 is handled a bit more freely, because some prefer to have the dot-based "catch all else" lexer rule match invalid chars, for example to produce a warning or error message. I wrote a section about this in the manual to explain how and why.
