### ISSUE TITLE
Please add fast lexer generators re2c and ragel to the benchmark.

### ISSUE THREAD

**Issue by skvadrik** [Genivia/RE-flex#86]
Hi!

I recently came over the RE-flex benchmark. It is very interesting and useful, thanks for making it!

I was a bit surprised _not_ to find [re2c](https://re2c.org/) and [ragel](https://www.colm.net/open-source/ragel/) among the competitors. They are both known for the speed of the generated code, so it should be more interesting for RE-flex to compare against them, and not flex, which is known to be slower.

Therefore I downloaded the benchmark source code, perfcomp.zip, as per [README.md](https://github.com/Genivia/RE-flex/blob/master/README.md) instructions and added benchmark files for re2c and ragel myself (and checked that they recognize the same 244 lexemes as the other engines). I attach the augmented archive [perfcomp_with_re2c_and_ragel.zip](https://github.com/Genivia/RE-flex/files/5173611/perfcomp_with_re2c_and_ragel.zip), which contains the following changes:

- Added file re2ctest.re
- Added file rageltest.rl
- Modified Makefile (added build rules for re2c and ragel, changed `-O2` to `-O3`)

In my setting (Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz, Linux with GCC-9.3.0) both re2c and ragel perform very fast (under 2 μs, re2c slightly faster in my setting but it really depends on the toolchain), even compared to RE-flex (which takes about 7 μs that seems to agree with your results). Note that I increased the `RUNS` count for the added benchmarks, because at 100 the timings are way too unstable for fast engines.

There are, of course, various useful things that RE-flex does but the newly added benchmarks do not, like tracking locations. However, since this benchmark is about the speed of the generated code, I think it makes sense for each engine to provide the fastest variant where it does as little as possible. And in practice one doesn't always need the extra stuff, often people just want a state machine that can go as fast as it can. I'm sure you can squeeze more speed out of RE-flex as well, but it's important to have fast competitors. 

I'm sorry to submit this in the form of an issue and not a ready-to-merge pull request, but I could not find benchmark source code in the RE-flex repository. Is there any reason you did not add it as a subdirectory in the RE-flex repo?

Finally, thanks for your work on RE-flex!

**Comment by genivia-inc** [comment]
I am surprised that the benchmarks in the README are misinterpreted for why they are included in the first place. It is clear what they are meant for: _to offer a fair comparison to Flex which has similar design and features as RE/flex_ (hence the name!).

The design choice for RE/flex is not to be the absolute fastest scanner generator on earth, although it comes close! Rather the RE/flex design aims to offer more useful features and flexibility compared to Flex by offering plug-in regex matchers, seamlessly accept various input formats and sources, and to be 99% compatible to Lex, Flex and Bison.

Lex/Flex is the de-facto standard tool and still the most popular lexer analyzer generator. The design goal of RE/flex is to extend the functionality of Flex while maintaining or increasing runtime performance. This is accomplished by various implementation optimizations in RE/flex that make scanners typically run faster than Flex++. There is also a choice of regex libraries that RE/flex supports.

That is what the benchmarks are showing and why they are included in the first place in the README.

RE/flex offers a modern C++ API, accepts Unicode input sources, supports (custom) file format pages to support legacy file formats, supports plug-in regex libraries, such as PCRE2, Boost.Regex, fuzzy regex matching, and much more. The runtime overhead of choosing PCRE2 and Boost.Regex with RE/flex are also shown in the benchmarks, which is practical for RE/flex users to understand.

As for re2c and regal, are they compatible to Flex and Bison? Are they a POSIX standard? No.

Therefore I disagree on adding re2c and ragel to the benchmarks. They are not compatible to Flex+Bison. They are much harder to use with Bison (not just plain Bison but Bison with options). Their limitations make them fast, but the (hidden) cost is usability. For example, the user has to implement input handling and add logic to implement start condition states, etc. 

Also, the benchmarks show performance without any shenanigans to make RE/flex run faster. This is done by focussing on a common use case (C source code) and by running the scanner from the command line (e.g. no CPU ramping up to improve the numbers).

As for the re2c to RE/flex raw speed comparison: when we limit RE/flex by ripping out the file/string/wide-string and UTF-8/16/32 input logic to bypass `reflex::Input` to fetch input data directly from memory and by ripping out the choice of regex engine, then this in fact makes RE/flex a lot faster (about 2x on my machine), which would be a fair comparison to re2c and put them more on par.

But that is not a practical use case to consider when comparing features versus performance.

RE/flex users commented that they value RE/flex's features over other tools. They do not ask for options to limit the functionality to increase speed further. What is important in their view is the compatibility with Flex+Bison and overall usability, as demonstrated in the examples, which practically covers all Flex+Bison use cases and many more practical examples, such as a Mini C compiler, that are easy to understand and implement with RE/flex. Another example is the Braille translator, which is easy in RE/flex but harder to understand in re2c and not even usable in re2c because it is incomplete (a complete implementation requires condition states and accepting UTF-8/16/32 input files!)

So the question for users is: what do you value more? Something that is a bit faster like re2c but very limited so you will likely end up spending a lot more time on coding to implement scanners (as I have done and I hated it), or RE/flex that is similar but faster than Flex++ so you can use all of the Flex examples in textbooks and the Flex and Bison manuals, and spend less time on learning RE/flex and spend less time on coding a scanner and spend more quality time on developing your application?

To summarize, it is not too hard to produce a scanner generator tool that is faster, but the cost is typically hidden elsewhere. In the case of re2c it is the aforementioned limitations of re2c and the runtime cost that ends up elsewhere, such as the necessity to add logic to decode UTF-8/16/32 file formats, as just one example.

> and not flex, which is known to be slower.

That is nonsense. As a researcher I've seen Flex performance comparisons that are valid but also comparisons that are bogus because they typically do not use the proper performance options and features of Flex that are documented in the manual. I have used Flex for over 20 years in various projects and in the graduate courses on compiler construction I taught. It is easy to make Flex run slow (the default is terrible). It is a harder to use Flex correctly to make sure it runs fast.

So whenever I hear "Flex is known to be slow" I don't trust the source of that claim.

**Comment by skvadrik** [comment]
Oh well, I wrongly assumed that this is an open competition for different engines because I saw that the benchmark includes a few regex libraries with different APIs in addition to RE-flex and Flex.

I'm putting together a benchmark for submatch-capable lexer generators myself (with a focus on speed), and I'd like to represent RE-flex in it as well. Would you be interested in having a look at it and giving some advice on how to best use RE-flex?

> As for re2c and regal, are they compatible to Flex and Bison? Are they a POSIX standard? No.

It is easy to use them with Bison (re2c own source code is one such example). As for the POSIX standard, there are various shades of conformance: many regexp engines support POSIX syntax, but I'm not aware of any lexer generator except re2c that supports POSIX longest-match submatch semantics correctly in all cases.

> Also, the benchmarks show performance without any shenanigans to make RE/flex run faster.

I wrote re2c and ragel code with no "shenanigans" either, in the natural way both tools are used.

> RE/flex users commented that they value RE/flex's features over other tools. They do not ask for options to limit the functionality to increase speed further.

No argument here. I have always been against of "one regexp engine to rule them all" approach.

> Another example is the Braille translator, which is easy in RE/flex but harder to understand in re2c and not even usable in re2c because it is incomplete (a complete implementation requires condition states and accepting UTF-8/16/32 input files!)

I'm not sure what you mean, but re2c has Unicode support out of the box (UTF-8/16/32, as well a few other encodings), and it has condition states, and even an example of partial [decoder from Grade-1 (uncontracted) Unicode English Braille to plain English](https://re2c.org/examples/c/reuse/example_braille.html).

> So the question for users is: what do you value more? Something that is a bit faster like re2c but very limited so you will likely end up spending a lot more time on coding to implement scanners (as I have done and I hated it), or RE/flex that is similar but faster than Flex++ so you can use all of the Flex examples in textbooks and the Flex and Bison manuals, and spend less time on learning RE/flex and spend less time on coding a scanner and spend more quality time on developing your application?

Oh, it depends. I just happen to be interested in run-time speed because it was absolutely essential in my work, which led me to learn about re2c. I'm sorry to hear, but not surprised, that you "hated" writing interface code for re2c lexers. I'm curious, when was the last time you tried it?

> So whenever I hear "Flex is known to be slow" I don't trust the source of that claim.

I wrote "slower" (than re2c), not "slow". It's usually around 2x due to the absence of one extra memory indirection that is present in table-based generators as opposed to direct-code generators, plus the re2c end-of-input handling that allows to make the checks less frequent or avoid them altogether. But you are right not to trust any claims not backed by code (that's why I want to put together a benchmark).

I do respect RE-flex mission and its users. I just thought that a healthy competition helps everyone (like GCC vs Clang). Sorry that I misunderstood the goal of your benchmark and wasted your time!

**Comment by genivia-inc** [comment]
> No argument here. I have always been against of "one regexp engine to rule them all" approach.

> I do respect RE-flex mission and its users. I just thought that a healthy competition helps everyone (like GCC vs Clang). Sorry that I misunderstood the goal of your benchmark and wasted your time!

I am not sure what you mean. One the one hand, you admit that you aren't keen of "one regex engine to rule them all", but on the other hand it appears that your goal is to produce benchmark results for the (sole?) purpose of a "healthy competition".

Personally I can agree with your first statement. As for competition, a user-oriented competition should focus on features and usability while trading the extra power with some minor performance impact that the user can live with. After all, there is no free lunch to have both in general. Moreover, the performance of a compiler, translator, or any tool that integrates a scanner, parser, and backend application logic is not determined by the performance of scanning but more often by the backend logic of the application.

Your GCC vs. Clang example is an apt choice to compare this to, since compiler speed isn't much of an issue any longer, but improved usability, such as better error reporting. If you have been in this field as long as I have, you know how poor C++ error reporting with GCC used to be!

Too many SW projects focussed solely on what can be technically accomplished and the designers forgot about the user. In the past that made sense, because machines were limited in speed and memory resources so it has to do (only) what the tool was designed to do, assuming the user would read the man page and had time to tinker until it works.

Our focus nowadays is "user experience (UX) design". My interpretation of this is to pursue perfection by technical innovation while listening to what the user wants and needs.

>> As for re2c and regal, are they compatible to Flex and Bison? Are they a POSIX standard? No.

> It is easy to use them with Bison (re2c own source code is one such example).

With all respect I disagree. Bison advanced practical use cases require combinations of bison-bridge, bison-locations, bison-complete, and direct access to the lexer state and semantic values. It is always easy for textbook-like examples. But it gets too complex quickly when scaling up, even a bit. As a consequence, tools like re2c are great but may become a showstopper for advanced use cases, or require far more effort to implement.

As a relatively simple example: consider a good Python tokenizer and parser that is both fast and compliant to the Python syntax standards. With RE/flex this is relatively easy (see the RE/flex examples). I've not yet found any Python-compliant lexer generator. Most tokenizers are written by hand. Not only for Python, but C# is entirely written with hand-coded scanners and recursive descent parsers. That is kind of ridiculous, but I can see why that choice was made.

> As for the POSIX standard, there are various shades of conformance: many regexp engines support POSIX syntax, but I'm not aware of any lexer generator except re2c that supports POSIX longest-match submatch semantics correctly in all cases.

I disagree. The IEEE POSIX P1003.2 standard defines portable standard versions of lex and yacc. That has nothing to do with POSIX regex syntax and matching. Flex has a simple ERE syntax with some minor additions such as quoting and trailing contexts. As for POSIX longest-match submatch semantics, I think you are confusing this with trailing contexts which are not well defined when there is overlap. Implementing a TDFA resolves the trailing contexts correctly, but there are not many practical cases for lexers that I can think of that need this. I am not aware of any trailing context issues for programming language and protocol tokenization. If there is a case of a trailing context issue, then the alternative is to use a start condition state.

>> Another example is the Braille translator, which is easy in RE/flex but harder to understand in re2c and not even usable in re2c because it is incomplete (a complete implementation requires condition states and accepting UTF-8/16/32 input files!)

> I'm not sure what you mean, but re2c has Unicode support out of the box (UTF-8/16/32, as well a few other encodings), and it has condition states, and even an example of partial decoder from Grade-1 (uncontracted) Unicode English Braille to plain English.

You should look at these examples more carefully. Your perception appears skewed by the re2c example. The re2c example Braille fragment was changed to pass their translator. The Braille decoder is only Grade-1, which is not useful at all due to incompleteness to decode practically all Braille texts used world-wide, which is essentially what I stated in my reply. RE/flex shows how to easily create a Grade-2 decoder and has the correct example that passes the test. This is just a minor gripe. My mantra is that if you do something then do it right.

Don't quote me wrong on Unicode. I did not state that Unicode matching is not possible with re2c. I find it a usability challenge. Technically there is always a way to decode UTF-8/16/32 with any scanner tool. But I disagree that re2c supports this "out of the box", because it is not automatic, just an addition of some extra code to use and add.

> Oh, it depends. I just happen to be interested in run-time speed because it was absolutely essential in my work, which led me to learn about re2c. I'm sorry to hear, but not surprised, that you "hated" writing interface code for re2c lexers. I'm curious, when was the last time you tried it?

Some of my more widely used work on compilers is [here](https://sourceforge.net/projects/gsoap2/). That project is about 20 years old now with over 1M downloads. Over time for projects I've used and tried different lexer/parser tools, re2c, Antlr, Boost.Spirit, to name a few.

A few years ago, I've tried re2c when implementing a C compiler for another project. This required Bison bridge+locations and access to the lexer state in the parser. I eventually switched back to Flex++, since it requires less effort to make it work properly.

Eventually I grew tired of using Flex++ as it has some known issues with certain option combinations and the fact that the generated code is hard to understand and not very C++ friendly from a technical perspective. So I wrote my own version and uploaded it here on GitHub.

The RE/flex generated code is optimized, but I could not sacrifice usability and risk losing compatibility with Lex/Flex POSIX standards, considering the fact that there are many Flex+Bison articles, books, and other resources that are also applicable to RE/flex.

The design choice to be compliant with Flex --- while adding modern features and producing "better" code --- means there is some runtime stuff with overhead, even though RE/flex runs comparably or faster than Flex++. I mentioned overhead before, but to be more specific: RE/flex uses an abstract matcher class for extensibility (virtual method invocation), the generated code uses a `switch` to enhance its readability (requires an extra jump per token), and automatically handles input formats with the "smart" `reflex::Input` class (adds more logic to retrieve input). Despite all of this, RE/flex is still faster in most cases than Flex, i.e. Flex with the best options for C++.

I can fairly easily create a simpler version of RE/flex that rips all of this stuff with overhead out in favor of more speed, likely getting about 2x speed up for the C tokenizer after a bit of rewriting it. But why? Just for the show and tell of benchmarking I suppose.

I'll get right on it when I have time.

**Comment by genivia-inc** [comment]
> I'm putting together a benchmark for submatch-capable lexer generators myself (with a focus on speed), and I'd like to represent RE-flex in it as well. Would you be interested in having a look at it and giving some advice on how to best use RE-flex?

IMHO it makes no sense to create a benchmark specifically for submatch-capable lexical analyzer generators, because there are very few that implement submatching. It is obvious that submatching can be very useful in contexts where regex pattern matching is used to search documents. However, I am not aware of any programming language tokenizer implementations (with or without lexical analyzers) that absolutely require submatching, group captures or complicated trailing context patterns. Furthermore, start condition states are typically used. Start condition states allow for efficient context-dependent pattern extraction and translation.

Sure, submatch extraction is useful in document search and queries, but so are lookahead and lookbehind for example, as well as other Perl regex syntax constructs. The Perl regex syntax is often more intuitive to use to formulate search patterns and it is sometimes essential because of its extensive regex features. Because RE/flex is also a regex engine for pattern matching and search, see for example the [ugrep project](https://github.com/Genivia/ugrep), I've considered adding Ville Laurikari's [TDFA](https://laurikari.net/ville/regex-submatch.pdf) --- which by the way is similar to Rob Pike's tagging of edges in his Sam Editor [as described here](https://link.springer.com/chapter/10.1007/978-3-642-37064-9_29) --- to RE/flex at a later date when I have time, or use an alternative DFA formulation that a graduate student of mine designed and explored for his MS, called [staDFA](http://fsu.digital.flvc.org/islandora/object/fsu%3A650269).

So no, I don't think it makes any sense to add Lex, Flex or RE/flex to a benchmark of submatch-capable lexer analyzers.

IMO a really useful feature of RE/flex are lazy quantifiers, because the greedy leftmost longest match rule of POSIX matching is essential for tokenization (i.e. rules are largely declarative), but also a trap. This trap can be easily avoided by using lazy quants where necessary.

**Comment by skvadrik** [comment]
Ah, I thought that RE/flex already is based on staDFA. That's how I got to know about it (from Chowdhury's thesis).

I got interested in submatch extraction a while ago, when I was trying to fix the lookahead operator in re2c (aka trailing context). It is known that Flex does not implement it correctly in all the cases, and re2c had the same error. As I was digging deeper into the problem, I realized that it is in fact a special case of submatch extraction, which itself is partial parsing.
 
I am the author of [lookahead TDFA extension](https://arxiv.org/abs/1907.08837) of Laurikari's TDFA, also briefly described in a [short article](https://doi.org/10.1016/j.simpa.2020.100027) about re2c. I implemented submatch extraction in re2c in 2016, and later in 2019 I came across staDFA paper, studied it for half a year and implemented the algorithm in re2c as well. I wrote a long email to Mohammad Imran about my findings, some necessary modifications that I had to make to his algorithm in order to produce correct results, and a few inaccuracies with regard to TDFA, but sadly he did not reply.

Now I'm gathering material for a more comprehensible paper about lookahead TDFA (the first one is cluttered with POSIX disambiguation problem, which is big enough to be considered in a [separate article](http://re2c.org/2019_borsotti_trofimovich_efficient_posix_submatch_extraction_on_nfa.pdf)), and a comparison of TDFA with staDFA and DSST (the automata used in [Kleenex](https://github.com/diku-kmc/kleenexlang)). I already have an implementation of staDFA in re2c, but I thought there is a different one in RE/flex, so I wanted to use that as well in my benchmarks. Apparently I was wrong and it is not integrated yet.

Of course, it does not make sense to add Lex or Flex to submatch benchmark, because they don't have submatch extraction (as you have noted, few lexer generators do).

**Comment by skvadrik** [comment]
To answer your earlier comment:

> You should look at these examples more carefully. Your perception appears skewed by the re2c example. The re2c example Braille fragment was changed to pass their translator. The Braille decoder is only Grade-1, which is not useful at all due to incompleteness to decode practically all Braille texts used world-wide, which is essentially what I stated in my reply. RE/flex shows how to easily create a Grade-2 decoder and has the correct example that passes the test. 

I wrote the example and I copy-pasted the example message from an article on the internet. I did not mangle it intentionally. There might have been errors in the original message, or it might have been a different Braille "flavor", but the claim that I modified the message to suit re2c is not true. As for the incompleteness, it's only an example to show the use of a few re2c options, and does not pretend to be a complete translator. It can be used as a starting point though.

> As a consequence, tools like re2c are great but may become a showstopper for advanced use cases, or require far more effort to implement.

Compared to other lexer generators, re2c has two main virtues (and reasons why people use it). The first virtue is the speed of the generated code. This matters for tools like [Ninja](https://ninja-build.org/) which need all the speed they can get. The second virtue it the flexibility of the user interface. It's a DIY approach: of course it allows one to shoot themselves in the foot, but it also allows one to do interesting things that others normally don't do. I'm not speaking from my personal experience here, but from the feedback provided by the re2c users.

**Comment by genivia-inc** [comment]
> Compared to other lexer generators, re2c has two main virtues...

I am super confident that RE/flex has merits and virtues too!

RE/flex is a modern C++ design and implementation of a lexical analyzer generator, producing very fast scanners. Unlike the other tools you mention, RE/flex is IEEE POSIX P1003.2 compliant i.e. compatible with Lex/Flex and Bison, works seamlessly with Bison complete parsers, bison locations, bison bridge. RE/flex also offers a choice of regex engines.

These are important considerations that users make when selecting a lexical analyzer generator for their projects. I have been in their shoes many times. Being in the trenches myself gives me some perspective of what works and what matters most when using a lexical analyzer and parser generator. Of course, I cannot speak for everyone and their projects.

But this is not the place and time to start a conversation about the merits of some (other) tools. There is no point in doing so, because those tools you are focussing on are functionally not equivalent to Flex and RE/flex.

**Comment by skvadrik** [comment]
> I am super confident that RE/flex has merits and virtues too!

No doubt about that. Otherwise I would not bother adding re2c and ragel to the benchmark!

> But this is not the place and time to start a conversation about the merits of some (other) tools.

I was answering your previous comment. Anyway, thanks for sharing your thoughts, for me the discussion was useful.

**Comment by genivia-inc** [comment]
Ulya, thanks again for your comments and suggestions. A couple of months have passed, but this has been on my mind to write a response with an explanation.

> I am the author of lookahead TDFA extension of Laurikari's TDFA, also briefly described in a short article about re2c. I implemented submatch extraction in re2c in 2016, and later in 2019 I came across staDFA paper, studied it for half a year and implemented the algorithm in re2c as well. I wrote a long email to Mohammad Imran about my findings, some necessary modifications that I had to make to his algorithm in order to produce correct results, and a few inaccuracies with regard to TDFA, but sadly he did not reply.

I'm dismayed that my former student Imran Chowdhury never replied to your email or shared your comments on staDFA with me so I could reply. This is not acceptable and I apologize for his lack of responsiveness. In hindsight, I made a mistake to accept Imran to my research group at FSU in early 2017. He turned out to be disrespectful to others and gave me and other faculty in the department trouble and some grief. I've advised and assisted many graduate students with projects, thesis and dissertations. I'm proud to see that they are all doing very well after graduation.

I handed Laurikari's paper "NFAs with Tagged Transitions" to Imran, because he seemed interested in this topic. The idea to investigate was to produce sub match-capable DFAs, but avoid tagged transitions to favor of tagged DFA states instead. Perhaps table-driven RE engines might be more efficient this way, from a practical and implementation point of view. That was the idea to investigate that led to staDFA. At that time, your paper "Tagged Deterministic Finite Automata with Lookahead" was not yet published. I recently read it with much interest. I also found issues with TDFA and staDFA POSIX sub-match extraction in the papers, when testing with the prototype Prolog implementation of these. That was one of the important reasons I put off considering this for RE/flex.

Note that RE/flex includes a Flex-compatible scanner generator, but the library has always been its core. The RE/flex library POSIX DFA engine can be used in C++ projects, such as [ugrep](https://github.com/Genivia/ugrep). Because regex are converted by such projects to DFA at *runtime* in the RE/flex engine, the engine is table-driven. These tables are more like a VM than DFA tables. I found by experimentation that VM execution is typically more efficient with memory resources than full DFA tables like Flex. The table-driven VM speed is comparable to the fastest full DFA tables of Flex. However, VM tables help to conserve memory to store DFAs of large regex, especially when UTF-8 byte sequences are represented in a DFA. And the VM tables represent direct code. Direct code is the fastest. The way RE/flex scanners emulate Flex introduces the same execution overhead that Flex has, using a loop to invoke the scanner and a switch to execute branches with actions in the generated scanner rather than directly jumping around with goto's on DFA transitions. However, the generated source code is very readable compared to Flex output (which is clearly not intended to be readable).

I plan to move forward implementing group captures and a trailing context fix in RE/flex. Backreferences are very useful too, but probably require some form of backtracking in the DFA. What is your assessment on backreferences to match input, e.g. `(a*)b\1`?

**Comment by skvadrik** [comment]
Hi Robert, thank you for your reply!

> I'm dismayed that my former student Imran Chowdhury never replied to your email or shared your comments on staDFA with me so I could reply. This is not acceptable and I apologize for his lack of responsiveness.

It's totally fine, in such cases I assume that the email got into spam, or the person is too busy with other things. I can share the details with you (perhaps it would be better to do it in a separate issue on github, this way we can keep it the open for anyone interested).

I have implemented sta-DFA with my corrections, and it works and passes all the same tests as TDFA. My experiments have shown that sta-DFA are about as fast as TDFA(1) in simple cases, but they grow in size much faster on large or ambiguous regular expressions (and as a result, get much slower than TDFA). You can see the [benchmark results](https://re2c.org/benchmarks/benchmarks.html#submatch-lexer-generators), at first there are real-world benchmarks, and then artificial series focused on alternative, concatenation and repetition. Both implementations go through the same optimization pipeline, so the comparison should be fair.

After I got the experimental results, I abandoned sta-DFA approach as less promising compared to TDFA(1). It also makes sense to me theoretically, because TDFA(1) pushes the operations on outgoing transitions and reduces the amount of conflicts, while sta-DFA keeps them in states. Of course, my intuition could be wrong and benchmark results biased, so if you find something new here please let me know.

I am slowly rewriting the paper on TDFA to be more detailed, more formal, less cluttered with POSIX disambiguation and to cover the work done by my fellow researcher Angelo Borsotti, but in principal the algorithm is the same. If you want to experiment with it there is also a recent presentation with pictures [here](https://re2c.org/2021_trofimovich_re2c_a_lexer_generator_based_on_lookahead_tdfa_(slides).pdf).

It is an interesting question how to efficiently encode operations in table-based lexers. It sounds doable, but not trivial and it would be interesting to know how you solved it.

> What is your assessment on backreferences to match input, e.g. (a*)b\1?

As far as I know, backreferences raise the language complexity from regular to context-sensitive, so my intuition is that the computational complexity should change accordingly. I saw a few papers or informal blog posts in the past that claimed to have solved backreferences in a computationally efficient way by concatenating two identical DFAs and doing some post-processing, but either I didn't read them in depth or the approach seems oversimplified to me. (But I had the same pessimistic feeling about submatch before I understood TDFA, so my intuition could be too conservative).

I have a demotivating example in mind: suppose we have a regexp `(a|aa)\1` and string `"aaa"`. There is a valid match here, which is `"aa"` (we cannot match the third `"a"`). But if we try the two-DFA approach, it would match the whole `"aaa"` (first two symbols would be matched by the first DFA, and the last one by the second DFA). Then we attempt post-processing on the matched string and fail, because `"aa"` in not equal to `"a"`.

What could be done to repair this? When we encounter the first final state (at the time when we matched `"aa"`), we can do the postprocessing and, since `"a"` is equal to `"a"`, we can record this as a potential match result, to be used later if longer attempts fail. Checking should take O(n), because we can simply cut the matched part of the input in two halves strictly in the middle, and compare the halves for equality.

But it is not as simple as it seems. This `(a|aa)\1` can be a small subexpression in a large and ambiguous regexp, and by the time we match `"aa"` we may not be in a final state. Ok, we can mark such "check-states" states somehow (bear in mind that a lot more "harmless" paths will go through them, triggering unnecessary checks). But even with check-states, it may be problematic to know where the start of the substring matching `(a|aa)\1` is (we may not know it in the middle of matching, when the submatch values are still uncertain and multiple possibilities exist).

I don't have a good solution for backreferences. The re2c philosophy is to not implement a feature unless it can be implemented efficiently (i.e. it's better to not have a feature at all than to have a slow feature). RE/flex philisophy may be different in this regard, but note that even well-known, widely-used and mostly POSIX-compatible regexp engines like RE2 do not support them.

**Comment by skvadrik** [comment]
> even with check-states, it may be problematic to know where the start of the substring matching `(a|aa)\1` is

Come to think of it, we can use the same approach as TDFA (or sta-DFA) and encode the nondeterministic checks in DFA states (one per NFA substate, or none if not needed). So we would have non-determinisitic check-states (one DFA state may have zero or more checks for different possible start positions of the substring).

**Comment by genivia-inc** [comment]
> I have implemented sta-DFA with my corrections, and it works and passes all the same tests as TDFA. My experiments have shown that sta-DFA are about as fast as TDFA(1) in simple cases, but they grow in size much faster on large or ambiguous regular expressions (and as a result, get much slower than TDFA).

You do realize that this means that your implementations of TDFA and staDFA are not asymptotically time-efficient, i.e. time is not linear _O_(_n_) in the length _n_ of the DFA pattern match?

I suspect that your transition function average asymptotic execution time is _O_(_m_) for `m` out-edges on average per DFA state, making your TDFA matching cost _O_(_nm_) on average instead of the linear time _O_(_n_). The _m_ will quickly grow in TDFA and staDFA (perhaps even more) for practical regex patterns that are typically large. I already collected experimental stats some time ago to compare DFAs, which both grow larger when markers are used, depending on the pattern). The _m_ originates from the conditional jump logic for direct-coded DFAs with if-then-else (rather than jump tables). That is why the (academic) community rejects the idea that direct-coded DFAs are (generally) faster than table-driven DFAs.

When considering the staDFA approach as an alternative, I did not care about the number of staDFA states that we end up with, because it is a memory resource cost, not a CPU resource cost to match a pattern! DFAs can grow exponentially in size anyway, theoretically. The important thing is that we need a way to avoid annotating DFA edges with markers, because a table-driven DFA would have to use a costly non-table-based transition function. Moving the markers to the states would remove that requirement and leave the efficient _O_(1) table-based transition functions intact.

It disappointing that backreferences are not part of TDFA. It makes TDFA useless for many users, such as users of search tools that don't need the get the positions of the sub match but rather want some context sensitivity in the pattern match.

Of course backreferences require backtracking (not just "post processing" with rejection, because there can be a failure to match before the final state is reached). With backtracking, the worst-case asymptotic running time becomes exponential in the number of backreferences in a regex pattern.

**Comment by skvadrik** [comment]
Sorry for a late reply!

> I suspect that your transition function average asymptotic execution time is O(m) for m out-edges on average per DFA state, making your TDFA matching cost O(nm) on average instead of the linear time O(n).

No, that's not the case. Direct-coded TDFA can use jump tables as well as DFA --- they don't need to perform actions in order to decide which state they need to jump to. The decision is taken in the same way as with ordinary DFA: it is based purely on the next input character. After the jump TDFA can perform additional actions, if needed (register operations) and then do another unconditional jump to the next state. In other words, direct-coded TDFA don't need to have a series of if-then-else statements, neither because they are TDFA, nor because they are direct-coded.

> You do realize that this means that your implementations of TDFA and staDFA are not asymptotically time-efficient, i.e. time is not linear O(n) in the length n of the DFA pattern match?

TDFA do have a pathological case which I describe in the [paper](https://arxiv.org/abs/1907.08837), page 21. It is related to counted repetition and what the paper calls _nondeterminism degree_  of  a tag. Counted repetition is a typical cause for exponential blowup of ordinary DFA as well, so it's not surprising. In that sense you can construct a bad RE that will blowup TDFA, but you can do that with DFA as well, so it doesn't sound like a reason to not use TDFA in other cases.

I also did experiments on large RE with submatch extraction to compare TDFA performance with simple DFA. My data (present in the above paper or in the [benchmarks](https://re2c.org/benchmarks/benchmarks.html#submatch-lexer-generators)) shows that for real-world RE the overhead on submatch extraction is small.

**Comment by firasuke** [comment]
> As for re2c and regal, are they compatible to Flex and Bison? Are they a POSIX standard? No.

There exists a [`flex mode` for `re2c`](http://re2c.org/manual/manual_c.html) (`--flex-syntax/-F`), and a comparison would be interesting.

Also I don't think `RE-flex` is a drop-in replacement for `flex`, am I mistaken?

**Comment by genivia-inc** [comment]
> Also I don't think `RE-flex` is a drop-in replacement for `flex`, am I mistaken?

Of course it is! RE/flex is a drop-in replacement for Flex++ (i.e. C++ mode only.)

This project includes many Flex examples from the Flex documentation and from other Flex-related publications to demonstrate this.

I taught Flex+Bison for 20 years in a graduate compiler construction course at FSU. I think I know these tools pretty well by now.
