### ISSUE TITLE
Handling invalid UTF input

### ISSUE THREAD

**Issue by dnicolodi** [Genivia/RE-flex#90]
In my lexer I use a construct like this:
```
. {
    unput(*yytext);
    BEGIN(INVALID);
}

<INVALID>[^ \t\r\n]+ {
    error(yylloc, yytext, yyleng);
    BEGIN(INITIAL);
    return YYerror;
}
```
to report invalid input and re-synchronize the scanner to the next character that is likely to produce a valid token. I would like to use this same construct also to catch invalid UTF input. However, I haven't found a way to replace the `[^ \t\r\n]+` pattern with something that stops matching at the first whitespace character and at the same time matches invalid input. Is there a way to do this?

**Comment by genivia-inc** [comment]
The dot `.` in RE/flex in Unicode mode (`%o unicode`) is self-synchronizing and matches multiple invalid bytes until the next character. The next character is not consumed, but may be invalid as well, also matched by a catch-all dot rule. See [Invalid UTF encodings](https://www.genivia.com/doc/html/index.html#invalid-utf). To answer your question, you cannot use bracket lists to match invalid Unicode, since character classes always represent valid input. You can use the dot rule in the `INVALID` start condition state like this:
~~~
<INVALID>{
[ \t\r\n] {
    error(yylloc, yytext, yyleng);
    BEGIN(INITIAL);
    return YYerror;
}
.   // skip (in)valid chars (until white space)
}
~~~
This example skips (in)valid characters until a single white space character is encountered. It consumes this white space character. If you don't want that, then use `less(0)` in the rule to shorten the match to a zero length.
