### ISSUE TITLE
Reflex does not allow matching the empty string

### ISSUE THREAD

**Issue by bredelings** [Genivia/RE-flex#98]
Hi,

I've translated a Haskell Alex lexer to flex, and am now thinking of translating it to REflex.  This would hopefully allow me to handle unicode properly.

The lexer has some weird rules that look like

```
<bol>[\n]      loc.lines(1); loc.step();
<bol>""/.      do something else that ends in yy_pop_state()
```
For the second rule, reflex complains and says:
```
lexer.l:137: error: malformed regular expression or unsupported syntax
error in regex at position 2
""/.
  \___empty expression
```
The second rule is suppose to match a character that is not a newline, but _not_ consume it.  This doesn't stall forever because the bol state gets popped.  Is it possible to have a pattern that matches the empty string and don't consume anything?

In the Alex syntax, such a pattern is indicated by `()`:
```
<bol> {
  \n                                    ;
  ^\# line                              { begin line_prag1 }
  ()                                    { do_bol }
}
```

On a slightly different tack, Haskell is indentation-sensitive, and I see that REflex has indent/dedent rules, which is really cool.  I'm not completely sure yet if these give EXACTLY the semantics in the standard.  But if so it would be quite nice, and might simplify the lexer substantially...  I see that https://github.com/Genivia/RE-flex/blob/master/examples/indent2.l has both indent/dedent rules and also nested comment rules. 

-BenRI

**Comment by genivia-inc** [comment]
Interesting case.

Technically this pattern matches a non-empty input pattern, but the trailing context is discarded and thus leaves nothing matched in the end. Perhaps this situation warrants an exception that allows empty patterns before the trailing context slash `/`. This is currently forbidden because it offers a loophole to match empty input that almost always leads to disaster with lexers hanging indefinitely on input. That is the reason why I personally don't like allowing this construct (but opinions don't matter). There are some scenarios when empty matches are OK, such as indentation rules, i.e. secondary dedents don't match any input but there is a stopping criterion.

That is why the use of `less(0)` is mentioned in the RE/flex documentation to use when switching states when the input should not be consumed. Note that you could replace this pattern quite easily as follows and use `less(0)` to discard the match:
~~~
<bol>\n   loc.lines(1); loc.step();
<bol>.     less(0); ... 
~~~
Again, this is problematic unless you switch states in the second rule.

**Comment by bredelings** [comment]
So I was thinking about this, and it seems like empty matches should lead to a warning, instead of being forbidden.  Warnings are normally used for things that are not actually wrong, but might indicate a problem.  Yes, people can use empty matches to shoot themselves in the foot, but it also seems pretty useful when using lexer states -- specifically to change the state if we do NOT match a specific pattern or patterns.

In addition to warnings, a few other ideas come to mind:

2. One possibility would be to add a specific symbol that refers to the empty string.  Then if users use this symbol, they would presumably be saying empty-string-yes-really-i-mean-it.  Alex seems to use '()' to mean "empty string", for example.

3. Another possibility would be to check if there are any lexer-states defined in the program.  If there aren't any lexer states defined, then presumably this would indeed lead to distaster.  Unless, I suppose, the user is doing something weird and complicated behind the lexer's back, but that can probably be ingored.

4. Another option would be to add a specific option to the file that enables empty strings like %enable_empty_match

**Comment by genivia-inc** [comment]
I am not sure if this is a good idea, to be honest. POSIX lex matches empty input for `^` and `$` which makes sense. And the problem with trailing contexts `r/s` is that they are not guaranteed i.e. can be "dangerous" when the `r` and `s` patterns overlap. Obviously, when `r` is allowed to be empty then `r` trivially overlaps with `s`. So an empty `r` is "dangerous", although flex has some ad-hoc logic to handle some cases where `r/s` in lex do not work.

**Comment by genivia-inc** [comment]
Closing this issue. RE/flex is compatible to Flex, but just does not permit `""/...` as trailing context since this results in infinite looping (a potential security issue) unless a `BEGIN state` transition is used in the action. Also `less(0)` can be used instead of an empty trailing context to look ahead in the input stream for any pattern.
